import Contracts.LocalObligationMacroSmoke.LocalObligationMacroSmoke
import Contracts.LocalObligationMacroSmoke.Spec
import Contracts.LocalObligationMacroSmoke.Invariants
import Contracts.LocalObligationMacroSmoke.Proofs.Basic
import Contracts.LocalObligationMacroSmoke.Proofs.Correctness
