#!/usr/bin/env python3
"""Profile Lean build time by module and emit a markdown queue.

Usage:
  python3 scripts/profile_lean_modules.py --output docs/LEAN_PERF_QUEUE.md
  python3 scripts/profile_lean_modules.py --fresh --output docs/LEAN_PERF_QUEUE.md
"""

from __future__ import annotations

import argparse
import shlex
import subprocess
import time
from dataclasses import dataclass
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DEFAULT_MODULES_FILE = ROOT / "scripts" / "lean_profile_modules.txt"
DEFAULT_OUTPUT = ROOT / "docs" / "LEAN_PERF_QUEUE.md"


@dataclass
class ModuleTiming:
    module: str
    seconds: float
    returncode: int


def _run(cmd: list[str]) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        cmd,
        cwd=ROOT,
        text=True,
        capture_output=True,
        check=False,
    )


def _load_modules(path: Path) -> list[str]:
    modules: list[str] = []
    for line in path.read_text(encoding="utf-8").splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("#"):
            continue
        modules.append(stripped)
    if not modules:
        raise ValueError(f"No modules listed in {path}")
    return modules


def _profile_modules(modules: list[str], fresh: bool) -> list[ModuleTiming]:
    timings: list[ModuleTiming] = []
    for module in modules:
        if fresh:
            clean = _run(["lake", "clean"])
            if clean.returncode != 0:
                raise RuntimeError(f"lake clean failed before {module}:\n{clean.stderr}")
        start = time.perf_counter()
        result = _run(["lake", "build", module])
        elapsed = time.perf_counter() - start
        timings.append(ModuleTiming(module=module, seconds=elapsed, returncode=result.returncode))
        if result.returncode != 0:
            raise RuntimeError(
                f"lake build {module} failed (exit {result.returncode})\n"
                f"stdout:\n{result.stdout}\n\nstderr:\n{result.stderr}"
            )
    return timings


def _render_markdown(timings: list[ModuleTiming], fresh: bool, modules_file: Path) -> str:
    rows = sorted(timings, key=lambda item: item.seconds, reverse=True)
    top = rows[:5]
    cmd = ["python3", "scripts/profile_lean_modules.py"]
    if fresh:
        cmd.append("--fresh")
    cmd.extend(["--modules-file", str(modules_file.relative_to(ROOT))])
    cmd_text = shlex.join(cmd)

    lines: list[str] = []
    lines.append("# Lean Performance Queue")
    lines.append("")
    lines.append(f"Generated by `{cmd_text}`.")
    lines.append("")
    lines.append(f"Mode: {'fresh build per module' if fresh else 'incremental (cached) build'}")
    lines.append("")
    lines.append("## Top Offenders")
    lines.append("")
    lines.append("| Rank | Module | Seconds |")
    lines.append("| ---: | :----- | ------: |")
    for idx, entry in enumerate(top, start=1):
        lines.append(f"| {idx} | `{entry.module}` | {entry.seconds:.2f} |")
    lines.append("")
    lines.append("## Full Profile")
    lines.append("")
    lines.append("| Module | Seconds |")
    lines.append("| :----- | ------: |")
    for entry in rows:
        lines.append(f"| `{entry.module}` | {entry.seconds:.2f} |")
    lines.append("")
    lines.append("## Next Actions")
    lines.append("")
    lines.append("1. Pick the top module and reduce broad `simp`/`unfold` usage via helper lemmas.")
    lines.append("2. Prefer targeted `lake build <Module>` during iteration; run full `lake build` before pushing.")
    lines.append("3. Re-run this profiler after each performance PR and compare top-5 movement.")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--modules-file", type=Path, default=DEFAULT_MODULES_FILE)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--fresh", action="store_true", help="Run `lake clean` before each module build")
    args = parser.parse_args()

    modules_file = args.modules_file
    if not modules_file.is_absolute():
        modules_file = ROOT / modules_file

    output = args.output
    if not output.is_absolute():
        output = ROOT / output

    modules = _load_modules(modules_file)
    timings = _profile_modules(modules, fresh=args.fresh)
    markdown = _render_markdown(timings, fresh=args.fresh, modules_file=modules_file)

    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(markdown, encoding="utf-8")

    print(f"Wrote Lean perf queue to {output.relative_to(ROOT)}")
    for entry in sorted(timings, key=lambda item: item.seconds, reverse=True):
        print(f"{entry.seconds:7.2f}s  {entry.module}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
