namespace DumbContracts.EvmAsm

-- Minimal EVM asm emitter (same calling convention as Yul).

def directProgramAsm : List String :=
  [ "entry:"
  , "PUSH0"
  , "CALLDATALOAD"
  , "PUSH1 0xe0"
  , "SHR"
  , "DUP1"
  , "PUSH4 0x7eba7ba6"
  , "EQ"
  , "PUSH tag_getSlot"
  , "JUMPI"
  , "DUP1"
  , "PUSH4 0xf2c298be"
  , "EQ"
  , "PUSH tag_setSlot"
  , "JUMPI"
  , "DUP1"
  , "PUSH4 0x02222aec"
  , "EQ"
  , "PUSH tag_addSlot"
  , "JUMPI"
  , "DUP1"
  , "PUSH4 0x49f583e3"
  , "EQ"
  , "PUSH tag_guardedAddSlot"
  , "JUMPI"
  , "PUSH4 0xb61d4088"
  , "EQ"
  , "PUSH tag_maxStore"
  , "JUMPI"
  , "PUSH0"
  , "DUP1"
  , "REVERT"
  , "tag_maxStore:"
  , "PUSH ret_maxStore"
  , "PUSH1 0x44"
  , "CALLDATALOAD"
  , "PUSH1 0x24"
  , "CALLDATALOAD"
  , "PUSH1 0x04"
  , "CALLDATALOAD"
  , "PUSH fn_maxStore"
  , "JUMP"
  , "ret_maxStore:"
  , "STOP"
  , "tag_guardedAddSlot:"
  , "PUSH ret_guardedAddSlot"
  , "PUSH1 0x24"
  , "CALLDATALOAD"
  , "PUSH1 0x04"
  , "CALLDATALOAD"
  , "PUSH fn_guardedAddSlot"
  , "JUMP"
  , "ret_guardedAddSlot:"
  , "STOP"
  , "tag_addSlot:"
  , "PUSH ret_addSlot"
  , "PUSH1 0x24"
  , "CALLDATALOAD"
  , "PUSH1 0x04"
  , "CALLDATALOAD"
  , "PUSH fn_addSlot"
  , "JUMP"
  , "ret_addSlot:"
  , "STOP"
  , "tag_setSlot:"
  , "PUSH ret_setSlot"
  , "PUSH1 0x24"
  , "CALLDATALOAD"
  , "PUSH1 0x04"
  , "CALLDATALOAD"
  , "PUSH fn_setSlot"
  , "JUMP"
  , "ret_setSlot:"
  , "STOP"
  , "tag_getSlot:"
  , "PUSH1 0x04"
  , "CALLDATALOAD"
  , "SLOAD"
  , "PUSH0"
  , "MSTORE"
  , "PUSH1 0x20"
  , "PUSH0"
  , "RETURN"
  , "fn_setSlot:"
  , "SSTORE"
  , "JUMP"
  , "fn_addSlot:"
  , "SWAP1"
  , "DUP2"
  , "SLOAD"
  , "ADD"
  , "SWAP1"
  , "SSTORE"
  , "JUMP"
  , "fn_guardedAddSlot:"
  , "SWAP1"
  , "PUSH0"
  , "SWAP2"
  , "DUP3"
  , "DUP3"
  , "GT"
  , "PUSH guardedAddSlot_ok"
  , "JUMPI"
  , "guardedAddSlot_check:"
  , "POP"
  , "GT"
  , "ISZERO"
  , "PUSH guardedAddSlot_revert"
  , "JUMPI"
  , "JUMP"
  , "guardedAddSlot_revert:"
  , "PUSH0"
  , "DUP1"
  , "REVERT"
  , "guardedAddSlot_ok:"
  , "DUP2"
  , "DUP2"
  , "SLOAD"
  , "ADD"
  , "SWAP1"
  , "SSTORE"
  , "PUSH0"
  , "PUSH guardedAddSlot_check"
  , "JUMP"
  , "fn_maxStore:"
  , "SWAP1"
  , "DUP3"
  , "SWAP1"
  , "DUP2"
  , "DUP2"
  , "GT"
  , "PUSH maxStore_then"
  , "JUMPI"
  , "maxStore_check:"
  , "GT"
  , "ISZERO"
  , "PUSH maxStore_else"
  , "JUMPI"
  , "maxStore_join:"
  , "POP"
  , "POP"
  , "JUMP"
  , "maxStore_else:"
  , "SSTORE"
  , "PUSH0"
  , "DUP1"
  , "PUSH maxStore_join"
  , "JUMP"
  , "maxStore_then:"
  , "DUP1"
  , "DUP4"
  , "SSTORE"
  , "PUSH maxStore_check"
  , "JUMP"
  ]

def pretty (lines : List String) : String :=
  String.intercalate "\n" lines ++ "\n"

end DumbContracts.EvmAsm
